parameters:
    images_directory: '%kernel.project_dir%/public/images'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    giphy_api_key: '%env(GIPHY_API_KEY)%'
    app_domain: '%env(APP_DOMAIN)%'

    router.request_context.host: 'overpower-neatly-democrat.ngrok-free.dev'
    router.request_context.scheme: 'https'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $giphyApiKey: '%giphy_api_key%'

    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder

    App\Command\GenerateRepositoriesCommand:
        arguments:
            $finder: '@Symfony\Component\Finder\Finder'

    App\Twig\AppExtension:
        tags: ['twig.extension']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    