parameters:
    images_directory: '%kernel.project_dir%/public/images'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    giphy_api_key: '%env(GIPHY_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder

    App\Command\GenerateRepositoriesCommand:
        arguments:
            $finder: '@Symfony\Component\Finder\Finder'

    App\Twig\AppExtension:
        tags: ['twig.extension']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

